version: '2'
services:

  db:
    image: postgres
    container_name: postgres
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "postgres:"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: libkeep

  syslog:
    build:
      context: .
      dockerfile: Dockerfile-syslog
    container_name: syslog_to
    ports:
      - "5514:514/udp"
    volumes:
      - ./log:/var/log

  app:
    build: .
    container_name: app
    environment:
      DEBUG: 0
      HOST: '0.0.0.0'
      PORT: 5000
      DB_PASSWORD: password
      DB_USER: libkeep
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: libkeep
    ports:
      - "5000:5000"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "app:"
