version: '2'
services:
  db:
    image: postgres
    container_name: postgres
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "postgres:"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: libkeep
    depends_on:
      - syslog
  syslog:
    build:
      context: .
      dockerfile: Dockerfile-syslog
    container_name: syslog
    ports:
      - "514:5514"
    volumes:
      - ./log:/var/log
  app:
    build: .
    command: python run.py
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - syslog
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:5514"
        tag: "app:"
